### ISSUE TITLE
add toggle knob for client logging

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/connect_vbms#102] opened 2015-11-06 18:25 UTC
[this](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/src/vbms/client.rb#L203-L205) bit of logging sticks tons of data in `/tmp/`, which can blow up in size when running in prod.

Worth not hanging on to data we don't want (as well) -- perhaps only keep this around when we're in debug mode?

**Comment by llimllib** [comment] 2015-11-06 18:34
Is this a duplicate of #101?

**Comment by paultag** [comment] 2015-11-06 18:36
@llimllib not sure - I didn't track down how `decrypt_message_xml` was using the filehandle. If it's needed for just that, can we rm to the tmpfile after we're done with it?

**Comment by llimllib** [comment] 2015-11-06 18:56
That logfile name is passed to the java invocation of the decryptor, via a log4j command line argument. We could totally `rm` the file after the wsse invocation, although it would be best to not create it in the first place.

**Comment by paultag** [comment] 2015-11-06 19:01
(Oh how I wish for `O_TMPFILE`)

**Comment by amoose** [comment] 2015-11-06 19:09
dupe of #101

**Comment by amoose** [comment] 2015-11-06 19:10
Thanks @paultag, I had just added #101 and @harrisj is picking it up

**Closed by amoose** 2015-11-06 19:09 UTC

**Comment by paultag** [comment] 2015-11-06 20:11
:+1: thank you!
